# Generated by Django 5.1.2 on 2025-05-29 20:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_empresa', models.IntegerField()),
                ('nombre_empresa', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('contrasena_empresa', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8)])),
                ('telefono_empresa', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8)])),
                ('correo_empresa', models.CharField(max_length=100)),
                ('direccion_empresa', models.TextField()),
                ('fecha_registro_empresa', models.DateTimeField(auto_now_add=True)),
                ('referenciaIMG_empresa', models.CharField(max_length=30)),
                ('estado_empresa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Intereses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interes', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InteresesUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intereses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.intereses')),
            ],
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_oferta', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nombre_puesto_oferta', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('vacantes_oferta', models.IntegerField()),
                ('ubicacion_oferta', models.CharField(max_length=30)),
                ('fecha_oferta', models.DateTimeField(auto_now_add=True)),
                ('salario_oferta', models.CharField(max_length=30)),
                ('descripcion_oferta', models.TextField()),
                ('referenciaIMG_oferta', models.CharField(max_length=30)),
                ('estado_oferta', models.CharField(max_length=30)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresas')),
                ('intereses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.intereses')),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaOfertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ofertas')),
            ],
        ),
        migrations.CreateModel(
            name='OfertasEmpresas',
            fields=[
                ('Ofertas_empresa_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresas')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ofertas')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_oferente', models.IntegerField()),
                ('telefono_oferente', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('referenciaIMG_oferente', models.CharField(max_length=30)),
                ('estado_oferente', models.CharField(max_length=30)),
                ('intereses', models.ManyToManyField(related_name='Usuarios', through='api.InteresesUsuarios', to='api.intereses')),
            ],
        ),
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ofertas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='interesesusuarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios'),
        ),
    ]
