# Generated by Django 5.1.2 on 2025-05-30 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='correo_empresa',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='identificacion_empresa',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nombre_empresa',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='telefono_empresa',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='usuario',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='identificacion_oferente',
            field=models.IntegerField(unique=True),
        ),
    ]
