# Generated by Django 5.1.2 on 2025-09-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionusuario',
            name='tema',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
