# Generated by Django 5.1.2 on 2025-05-31 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_empresas_correo_empresa_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interesesusuarios',
            unique_together={('usuario', 'intereses')},
        ),
    ]
