# Generated by Django 5.1.2 on 2025-09-14 06:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registrotemporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotemporal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
