# Generated by Django 5.1.2 on 2025-09-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registrotemporal_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrotemporal',
            name='uuid',
        ),
    ]
