# Generated by Django 5.1.2 on 2025-06-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_interesesusuarios_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='referenciaIMG_oferente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
