# Generated by Django 5.1.2 on 2025-06-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuarios_referenciaimg_oferente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interesesusuarios',
            unique_together=set(),
        ),
    ]
