# Generated by Django 5.1.2 on 2025-06-04 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_users_usuarios_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='contrasena_empresa',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='correo_empresa',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='fecha_registro_empresa',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='nombre_empresa',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Users_Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresas',
            name='empresa_info',
            field=models.ManyToManyField(related_name='Empresas', through='api.Users_Empresas', to=settings.AUTH_USER_MODEL),
        ),
    ]
