# Generated by Django 5.1.2 on 2025-06-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_empresas_contrasena_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='identificacion_empresa',
            field=models.BigIntegerField(unique=True),
        ),
    ]
