# Generated by Django 5.1.2 on 2025-06-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_empresas_identificacion_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='direccion_empresa',
            new_name='ubicacion_empresa',
        ),
    ]
