# Generated by Django 5.1.2 on 2025-06-10 20:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_direccion_empresa_empresas_ubicacion_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='estado_oferta',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='referenciaIMG_oferta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='titulo_oferta',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
