# Generated by Django 5.1.2 on 2025-06-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ofertas_empresa_alter_ofertas_estado_oferta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertas',
            old_name='empresa',
            new_name='empresaUser',
        ),
    ]
