# Generated by Django 5.1.2 on 2025-06-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_empresas_referenciaimg_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaofertas',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ubicacion_empresa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='salario_oferta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
