# Generated by Django 5.1.2 on 2025-06-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_auditoriaofertas_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulaciones',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postulaciones',
            name='referenciaPDF',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OfertasEmpresas',
        ),
    ]
