# Generated by Django 5.1.2 on 2025-06-25 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_postulaciones_usuario_postulaciones_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CYSMensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('apellido', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('asunto', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fingerprint', models.CharField(max_length=64)),
            ],
        ),
    ]
