# Generated by Django 5.1.2 on 2025-06-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cysmensajes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CYSMensajes',
        ),
    ]
