# Generated by Django 5.1.2 on 2025-09-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_categoria_proveedor_remove_empresas_empresa_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='informacionusuario',
            name='identificacion',
        ),
    ]
